### ISSUE TITLE
Node fields based on other node fields (i.e. references)

### ISSUE THREAD

**Issue by pauleveritt** [Undistraction/gatsby-plugin-node-fields#3]
I have a homegrown setup that I'm interested in transferring to gatsby-plugin-node-fields but I'm not quite sure I can get there.

## Use Case

My markdown files have a ``type`` field which lets a document say it is an ``article``. In the frontmatter it can set an ``author``, a series of zero or more ``topics``, etc.

Where do ``author`` and `topic` come from? They are also markdown files: ``type: 'author'`` and ``type: 'topic'`` respectively. Thus, I have references.

## First Implementation: page query

I was previously resolving the references in the page query by grabbing all the topics and authors, then in the JS, finding the right one and picking out the data. That sucked. It was slow and I repeated tons of GraphQL everywhere. I also got no validation of broken references until viewing a page.

## Current Implementation: ``sourceNodes``

I now do this in ``sourceNodes``. First I walk the universe making a mapping of references. I then walk each node and make a new field, with the flattened reference.

Works well, except for authors. They write a new topic and...it doesn't work. Restarting doesn't work. They have to ``rm -rf .cache/*`` and restart. This is true for any change on anything that is referenced. Terrible experience for content authoring, obviously.

## Your Plugin

I see you are using ``onCreateNode`` and you have the idea of a context that is passed in. I wonder if that's enough:

- I don't think changes to a referenced node would trigger the update to the referencing node

- ``sourceNodes`` has access to the whole node tree, but I don't think ``onCreateNodes`` does

Perhaps I'm barking up the wrong tree, or perhaps I'm thinking about it wrong. And sorry for writing a novel. :(

**Comment by Undistraction** [comment]
@pauleveritt Sorry for taking so long to get back to you. If I follow you correctly, you're suggesting that the plugin should use`sourceNodes` as its hook instead of `onCreateNode`? \

**Comment by pauleveritt** [comment]
@Undistraction Neither are a good fit. sourceNodes doesn't run after startup and doesn't fire when the relationship target changes, so I have to delete the cache. onCreateNode would have to import "sourceNodes" and blow away everything on each change, in order to update the targets.

I think the problem is, mapping doesn't influence the dependency tree on rebuilds.

I had to give up on using lifecycle APIs and move everything back to page queries.  All of my queries have to request all of my posts, authors, and categories, then pick out which apply in a specific post. I still have to delete the cache on production builds as it still messes up sometimes.

If the use of mapping (a) did develop/build rebuilds accurately and (b) could handle 1:N reverse relationships, I'd be thrilled. Huge chunks of my per-page code would disappear.

**Comment by pauleveritt** [comment]
@Undistraction I should have mentioned, I logged a ticket about this at https://github.com/gatsbyjs/gatsby/issues/11151

**Comment by Undistraction** [comment]
Closing as this isn't something this library can solve.
