### ISSUE TITLE
Accessing other nodes in predicate

### ISSUE THREAD

**Issue by bravo-kernel** [Undistraction/gatsby-plugin-node-fields#6]
Love the idea of this plugin ❤️ . 

Would it be possible to access another node in the predicate? In this example-predicate I'm trying to access the parent node but thus far without any success as I only have `node` to play with. 

In the example below the `isMdxFile()` predicate function should be able to use `getNode`:

```js
const descriptors = [
  {
    predicate: isMdxFile,
    fields: [
       {
        name: 'author',
        getter: node => node.frontmatter.author,
        defaultValue: 'default-author',
      },
    ]
  }
]
```

```js
function isMdxFile(node) {
  if (node.internal.type !== "Mdx") {
    return false;
  }

  const parent = getNode(node.parent)
  if (parent.internal.type !== "File") {
    return false;
  }

  return true;
}
```

**Comment by Undistraction** [comment]
@bravo-kernel cheers.

Strangely enough I had the exact same need this week. Wanted to access a property on a Remark node's parent file node to add it as a field prop.

To access the parent a function needs access to the `getNode` helper that is one of the helpers passed in to `createNode`. That way it can get the of of the parent node with `node.parent`, then use `getNode(I'd)` to access the actual parent node.

I'm going to try and get this added this week, but need to think about the best way to do it. Worst case will be via an undocumented argent in the short term.

**Comment by bravo-kernel** [comment]
Right, it would be awesome if getNode itself could be passed as the second argument. This was suggested on Gatsby Discord as well btw. If you lack time I can take care of the documentation part once you land the feature.

**Comment by Undistraction** [comment]
@bravo-kernel Just published v3. All functions now get `getNode` as a final arg so you can do:

```
getter: (node, context, actions, getNode) => {
    // Get parent node
    const parent = pipe(
      prop(`parent`),
      getNode
    )(node)

    // Get it's type
    const type = pipe(
      prop(`sourceInstanceName`),
      pluralize.singular
    )(parent)

    return type
}
```

**Comment by bravo-kernel** [comment]
Thanks for the quick response, good job 👍

**Comment by bravo-kernel** [comment]
@Undistraction just tested the new version and even though `getNode` now works for the getters, it does not for the predicate.

Any chance we can pass `getNode` as the second argument for the predicate functions ?

**Comment by bravo-kernel** [comment]
Updated the initial code sample to make things more clear, hopefully

**Comment by Undistraction** [comment]
@bravo-kernel Ah sorry. I solved my use-case but not yours. That makes sense to me. I'll get that done later today, unless you fancy a quick PR.

Think it's as simple as passing `getNode` from `attachFields` into `appliesToNode` as the second arg.

See: https://github.com/Undistraction/gatsby-plugin-node-fields/blob/e4f437c497de8912f9632242466c839b0e4a35bc/src/internal/attachFields.js#L63

**Comment by bravo-kernel** [comment]
@Undistraction thanks for the pointer, I am willing to give this a shot but that will not be possible until at least tomorrow or somewhere this weekend. Would be interesting though, I had already skimmed the code but the ramda was making me kind of dizzy 😆

**Comment by bravo-kernel** [comment]
Simply put.. if you could make the change I would be very grateful as it would save me a lot of time. I will probably understand things better once the change has been applied.

**Comment by Undistraction** [comment]
@bravo-kernel no problem. I'll try and get it done today. 

FWIW I strongly recommend learning ramda. You will write much terser, simpler code with a lot less bugs. It will change the way you code and you'll never go back.

**Comment by Undistraction** [comment]
@bravo-kernel Just pushed 3.1.0 which now passes `getNode` as the second argument to the predicate.

**Comment by bravo-kernel** [comment]
Just tested and works like a charm. Highly appreciated 👍 

ps: I will surely invest some time in Ramda, you are not the only one advizing it
